# Build code documentation and deploy to "gh-pages" branch
name: Deploy Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The workflow needs to be able to write to the "gh-pages" page
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "generate"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install doxygen=1.9.1-2ubuntu2

      - name: Build docs
        run: doxygen
      
      # ensures pages with underscores work on gh pages
      - name: Create .nojekyll
        run: touch docs/reference/html/.nojekyll
        shell: bash

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/reference/html
